title: "Filippo Rossi"
username: "Qu4k"
profile_picture: "/assets/img/profile.jpg"

email: "filippo@filipporossi.me"
description: >-
  Personal portfolio and blog. Posts about programming and
  gamedev.
baseurl: ""
url: "https://filipporossi.me"
twitter_username: "filipporeds"
github_username: "qu4k"
keybase_username: "filipporossi"
rss: "RSS Feed"

# Post settings
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-octicons_v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
