title: "Filippo Rossi"
username: "Qu4k"
profile_picture: "https://gravatar.com/avatar/c6f9b5cada1f83e998c40ed89a929990?s=400&d=robohash&r=x"

email: "filippo@filipporossi.me"
description: >-
  Personal portfolio and blog. Posts about programming and
  gamedev.
baseurl: ""
url: "https://filipporossi.me"
twitter_username: "filipporeds"
github_username: "qu4k"
keybase_username: "filipporossi"
rss: "RSS Feed"

# Post settings
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
