name: CI publish

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coauthor_email: filipporeds@users.noreply.github.com
        coauthor_name: filipporeds
        empty: true
